### ISSUE TITLE
migration failed

### ISSUE THREAD

**Issue by innubies** [gurock/testrail-docker#57]
I have migration's error when I upgrade testrail from 6.6 to 7.5

`== 20220111140001 AddPrivateKeyToSsoSettingsTable: migrating
PDOException: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'saml_encryption_private_key' in /opt/testrail/vendors/phinx/Db/Adapter/PdoAdapter.php:217
Stack trace:
#0 /opt/testrail/vendors/phinx/Db/Adapter/PdoAdapter.php(217): PDO->exec()
#1 /opt/testrail/vendors/phinx/Db/Util/AlterInstructions.php(112): Phinx\Db\Adapter\PdoAdapter->execute()
#2 /opt/testrail/vendors/phinx/Db/Adapter/PdoAdapter.php(643): Phinx\Db\Util\AlterInstructions->execute()
#3 /opt/testrail/vendors/phinx/Db/Adapter/PdoAdapter.php(1018): Phinx\Db\Adapter\PdoAdapter->executeAlterSteps()
#4 /opt/testrail/vendors/phinx/Db/Adapter/AdapterWrapper.php(484): Phinx\Db\Adapter\PdoAdapter->executeActions()
#5 /opt/testrail/vendors/phinx/Db/Adapter/TimedOutputAdapter.php(434): Phinx\Db\Adapter\AdapterWrapper->executeActions()
#6 /opt/testrail/vendors/phinx/Db/Plan/Plan.php(153): Phinx\Db\Adapter\TimedOutputAdapter->executeActions()
#7 /opt/testrail/vendors/phinx/Db/Table.php(722): Phinx\Db\Plan\Plan->execute()
#8 /opt/testrail/vendors/phinx/Db/Table.php(629): Phinx\Db\Table->executeActions()
#9 /opt/testrail/vendors/phinx/Db/Table.php(688): Phinx\Db\Table->update()
#10 /opt/testrail/db/migrations/20220111140001_add_private_key_to_sso_settings_table.php(28): Phinx\Db\Table->save()
#11 /opt/testrail/vendors/phinx/Migration/Manager/Environment.php(112): AddPrivateKeyToSsoSettingsTable->up()
#12 /opt/testrail/vendors/phinx/Migration/Manager.php(382): Phinx\Migration\Manager\Environment->executeMigration()
#13 /opt/testrail/vendors/phinx/Migration/Manager.php(356): Phinx\Migration\Manager->executeMigration()
#14 /opt/testrail/vendors/phinx/Console/Command/Migrate.php(123): Phinx\Migration\Manager->migrate()
#15 /opt/testrail/vendors/symfony/console/Command/Command.php(256): Phinx\Console\Command\Migrate->execute()
#16 /opt/testrail/vendors/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run()
#17 /opt/testrail/vendors/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand()
#18 /opt/testrail/vendors/phinx/Console/PhinxApplication.php(69): Symfony\Component\Console\Application->doRun()
#19 /opt/testrail/vendors/phinx/Wrapper/TextWrapper.php(239): Phinx\Console\PhinxApplication->doRun()
#20 /opt/testrail/vendors/phinx/Wrapper/TextWrapper.php(117): Phinx\Wrapper\TextWrapper->executeRun()
#21 /opt/testrail/sys/libraries/migrations.php(76): Phinx\Wrapper\TextWrapper->getMigrate()
#22 /opt/testrail/app/models/update.php(123): Migrations_library->getMigrate()
#23 /opt/testrail/app/controllers/updater.php(418): Update_model->migrate()
#24 /opt/testrail/sys/base/controller.php(257): Updater_controller->ajax_run_migration()
#25 /opt/testrail/sys/base/controller.php(168): Controller->_invoke_web_call()
#26 /opt/testrail/sys/base/controller.php(120): Controller->_invoke_web()
#27 /opt/testrail/sys/core/gizmo.php(129): Controller->_invoke()
#28 /opt/testrail/index.php(114): require_once('/opt/testrail/s...')
#29 {main}`

I think column was created previous migration because I've checked database before and column wasn't exist.

**Comment by jazerix** [comment]
TestRail's migration scripts is nothing short of an abomination. The migrate script is effectively broken on their 7.4 and on 7.5 it fails to migrate everything. For a company that creates QA software it's unfathomable that they do **ZERO** QA on their docker images.

I ended up having to create a custom script that would gradually reinsert our attachments into the MySQL database one by one and then calling the migrate script each time and then lastly restoring all of the old attachments, which seems to work.

**Comment by prawal10** [comment]
Hi @jazerix I am also facing some issue with the migration script. Is it possible to share the script you have created? Thank you in advanced.

**Comment by jazerix** [comment]
@prawal10 Certainly, I've uploaded a gist here: https://gist.github.com/jazerix/0553dc023428f519f43769f1f8cd4470

Be sure to read the comment below as it describes the procedure.
